### ISSUE TITLE
Could you add that to the Sublime Package Control?

### ISSUE THREAD

**Issue by optikfluffel** [Hugoch/sublimeText2-mustache#1]
Hey :)
Could you please add this thing to the [Sublime Package Control](http://wbond.net/sublime_packages/package_control/package_developers)? It's so nice to install and update stuff with that ^^

Greetings from Berlin, optikfluffel

**Comment by Hugoch** [comment]
Yep, I'll do it ASAP !

**Comment by optikfluffel** [comment]
thanks :)
